
#pragma once

#include <sys/types.h>

/* Declarations for required implementation functions in slash.c */
void slash_command_usage(slash_t *slash, struct slash_command *command);
char *slash_history_increment(slash_t *slash, char *ptr);
int slash_putchar(slash_t *slash, char c);
struct slash_command * slash_command_find(slash_t *slash, char *line, size_t linelen, char **args);
void slash_command_description(slash_t *slash, struct slash_command *command);

/* Define and initialize section variables */
/* __attribute__((visibility("hidden"))) prevents the section symbols from linking with
	the loading application (csh) when compiling an APM.
	In simple terms: When used alone, this means the APM must define at least 1 command,
	(so "__start_slash" will be generated by GCC) before it can use slash as a dependency.
    But when combined with 'weak' the value will be NULL, instead of linking with the sections in CSH. */
extern struct slash_command __start_slash __attribute__((visibility("hidden"), weak));
extern struct slash_command __stop_slash __attribute__((visibility("hidden"), weak));
